language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t arnajdas92/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true arnajdas92/docker-react npm run test -- --coverage
